/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Shutdown */

#ifndef _Included_Shutdown
#define _Included_Shutdown
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Shutdown
 * Method:    shutdownWindows
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Shutdown_shutdownWindows
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
