/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main1 */

#ifndef _Included_main1
#define _Included_main1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main1
 * Method:    sqr
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_main1_sqr
  (JNIEnv *, jclass, jint);

/*
 * Class:     main1
 * Method:    cub
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_main1_cub
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
